services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-stride}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
