spring:
  application:
    name: stride
  datasource:
    url: jdbc:postgresql://localhost:5432/stride
    username: postgres
    password: changeit
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
